//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bukuHuga
{
    using System;
    using System.Collections.Generic;
    
    public partial class aksesBuku
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public aksesBuku()
        {
            this.Transaksis = new HashSet<Transaksi>();
        }
    
        public int idBuku { get; set; }
        public string namaBuku { get; set; }
        public string namaPenulis { get; set; }
        public int hargaBuku { get; set; }
        public int stokBarang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaksi> Transaksis { get; set; }
    }
}
