//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bukuHuga
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bukuEntities3 : DbContext
    {
        public bukuEntities3()
            : base("name=bukuEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aksesBuku> aksesBukus { get; set; }
        public virtual DbSet<userAkun> userAkuns { get; set; }
        public virtual DbSet<Transaksi> Transaksis { get; set; }
    }
}
